using System.Text.Json.Serialization;

namespace VirtualDevTeam.Core.Pipeline;

/// <summary>
/// A snapshot of where a PR sits in the merge-flow lifecycle. Generated by
/// <see cref="IPrMergeFlowSource"/> per request. Cached for ~10s server-side.
/// </summary>
public sealed record PrMergeFlowSnapshot
{
    public required int PrNumber { get; init; }
    public required DateTime ComputedAt { get; init; }
    public required IReadOnlyList<PrMergeFlowStep> Steps { get; init; }
    public required PrMergeFlowSummary Summary { get; init; }
}

/// <summary>
/// Aggregated summary of a PR's current merge-flow position, used to populate
/// status badges without requiring the caller to scan the full step list.
/// </summary>
public sealed record PrMergeFlowSummary
{
    public required string? CurrentStepId { get; init; }
    public required int CompletedCount { get; init; }
    public required int TotalApplicableCount { get; init; }
    public required int StuckSeconds { get; init; }   // age in current state; for the ⏱ badge
}

/// <summary>
/// One step in the canonical merge-flow lifecycle. Order: branch-created → implementation
/// → self-assessment → architect-review → pm-review → se-peer-review → te-inline-tests →
/// security-audit → human-gate → mergeable-ci → merge.
/// </summary>
public sealed record PrMergeFlowStep
{
    public required string Id { get; init; }              // stable: "self-assessment", "architect-review", "pm-review", …
    public required string Title { get; init; }           // display: "PM Review"
    public required string Icon { get; init; }            // emoji marker for the strip
    public required PrMergeFlowStepState State { get; init; }
    public required int Lane { get; init; }               // R5: 0 = main sequence, 1+ = parallel lanes
    public string? Detail { get; init; }                  // one-line summary
    public string? Tooltip { get; init; }                 // hover popover text
    public string? WhatsNeeded { get; init; }             // for Pending: required preconditions
    public string? WhatsBlocking { get; init; }           // for Blocked: blocker description + remediation hint
    public string? OwningAgentRole { get; init; }         // R4: stable role name (ProgramManager, Architect, …)
    public string? OwningAgentId { get; init; }           // R4: optional current instance ID (may be null on restart)
    public string? OwningAgentDisplayName { get; init; }  // for human-friendly display
    public DateTime? StartedAt { get; init; }
    public DateTime? CompletedAt { get; init; }
    public DateTime? FailedAt { get; init; }
    public IReadOnlyList<string>? RelatedLogLines { get; init; }
    public IReadOnlyList<StateTransition> StateTransitions { get; init; } = Array.Empty<StateTransition>();
    public IReadOnlyList<string>? RelatedFlowFindingIds { get; init; }   // Direction B integration with FlowMonitor
}

/// <summary>R3 from rubber-duck: per-step state history. Stored in snapshot
/// (last 5 transitions), persisted long-term via PrStepHistoryStore (Phase 2).</summary>
public sealed record StateTransition
{
    public required PrMergeFlowStepState From { get; init; }
    public required PrMergeFlowStepState To { get; init; }
    public required DateTime At { get; init; }
    public string? Reason { get; init; }
}

/// <summary>
/// Lifecycle state for a single step in the merge-flow pipeline.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PrMergeFlowStepState
{
    NotApplicable,   // ⊘ gate disabled by config / irrelevant to this PR type
    Pending,         // ○ not yet started
    InProgress,      // ● actively being worked on
    Done,            // ✓ completed successfully
    Failed,          // ✗ encountered an error — needs attention
    Skipped,         // ↷ intentionally skipped (e.g. no-op gate cleared without action)
    Blocked,         // ⏸ can't proceed — external blocker (waiting on human, etc.)
}
