using System.Text.Json.Serialization;

namespace VirtualDevTeam.Core.MissingWork;

/// <summary>
/// A finding emitted by an <see cref="IMissingWorkDetector"/> reporting work that appears
/// to be implicitly required by the codebase (placeholders, phantom task references, unwired
/// assets, naming mismatches, etc.) but is not currently tracked as an open or recently-closed
/// issue. Findings are persisted, optionally enriched into a structured proposed issue by
/// <see cref="IMissingWorkPlanner"/>, and surfaced on the Approvals page for operator review.
/// </summary>
public sealed record MissingWorkFinding
{
    public required string Id { get; init; }

    /// <summary>Stable identifier of the detector that produced this finding (e.g. "phantom-task-reference").</summary>
    public required string DetectorId { get; init; }

    /// <summary>The specific pattern matched (e.g. "T14 art pipeline" for a phantom-task-reference).</summary>
    public required string Pattern { get; init; }

    /// <summary>One-line summary of the gap, for operator-facing notification text.</summary>
    public required string Summary { get; init; }

    /// <summary>File:line citations supporting the finding.</summary>
    public required IReadOnlyList<EvidenceCitation> Evidence { get; init; }

    /// <summary>Confidence score 0.0..1.0. Findings below the planner's threshold are dropped.</summary>
    public required double Confidence { get; init; }

    /// <summary>Stable key used to suppress re-emission within the dedup window.</summary>
    public required string DedupKey { get; init; }

    public DateTime DetectedAt { get; init; } = DateTime.UtcNow;
}

/// <summary>
/// A single piece of evidence supporting a MissingWorkFinding.
/// </summary>
public sealed record EvidenceCitation
{
    public required string FilePath { get; init; }
    public int? LineNumber { get; init; }
    public string? Snippet { get; init; }

    /// <summary>Optional kind hint: "comment", "field-decl", "config-key", "asset-path", etc.</summary>
    public string? Kind { get; init; }
}

/// <summary>
/// A proposed engineering-task issue derived from one or more <see cref="MissingWorkFinding"/>s.
/// Generated by <see cref="IMissingWorkPlanner"/>, persisted to the proposed_issues table,
/// surfaced on the Approvals page, and on operator approval becomes a real issue
/// via <see cref="VirtualDevTeam.Core.DevPlatform.Capabilities.IWorkItemService"/>.
/// </summary>
public sealed record ProposedIssue
{
    public required string Id { get; init; }
    public required string FindingId { get; init; }
    public required string DetectorId { get; init; }
    public required ProposedIssueState State { get; init; }
    public required string ProposedTitle { get; init; }
    public required string ProposedBody { get; init; }
    public required IReadOnlyList<string> ProposedLabels { get; init; }
    public IReadOnlyList<int> ProposedDependsOn { get; init; } = Array.Empty<int>();
    public IReadOnlyList<int> ProposedBlocks { get; init; } = Array.Empty<int>();
    public required double Confidence { get; init; }
    public required IReadOnlyList<EvidenceCitation> Evidence { get; init; }
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

    public DateTime? OperatorActionAt { get; init; }
    public OperatorAction? OperatorAction { get; init; }
    public string? OperatorRationale { get; init; }

    public string? FinalTitle { get; init; }
    public string? FinalBody { get; init; }
    public IReadOnlyList<string>? FinalLabels { get; init; }

    public int? CreatedIssueNumber { get; init; }
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ProposedIssueState { Pending, Approved, Rejected, Created, Superseded }

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OperatorAction { ApproveAsIs, ApproveEdited, Reject }
