namespace VirtualDevTeam.Core.HealthMonitor;

/// <summary>
/// Lifecycle state of a FixRecommendation produced by the FlowMonitor's two-pass
/// rubber-duck planner. New rows start at <see cref="Draft"/>, transition to
/// <see cref="PendingReview"/> once the plan is persisted to disk and visible on the
/// Approvals page, then to <see cref="ApprovedForCoding"/> when the operator approves.
///
/// T1.6 introduced tier-routed terminal states. Once the operator approves, the
/// approve endpoint classifies the recommendation and transitions to one of:
/// <see cref="Applied"/> (Live tier — config/prompt change reloaded automatically),
/// <see cref="Coded"/> (DeferredRestart tier — file written, runner restart needed to
/// activate), <see cref="StagedForNextRestart"/> (Blocked tier — saved for the next
/// boot), or <see cref="AppliedFailed"/> (CLI scope violation or build failure).
/// <see cref="ApprovedForCoding"/> is a transient state; the request handler advances it
/// before returning so the operator never sees a stale "Approved" status.
/// </summary>
public enum FixRecommendationState
{
    /// <summary>Just generated, not yet visible to operator.</summary>
    Draft,
    /// <summary>Persisted + on Approvals page, awaiting operator decision.</summary>
    PendingReview,
    /// <summary>Operator approved — transient state until tier routing kicks in.</summary>
    ApprovedForCoding,
    /// <summary>T1.6 Live tier: fix has been applied; config auto-reloaded; no restart.</summary>
    Applied,
    /// <summary>T1.6 DeferredRestart tier: code written; runner restart required to activate.</summary>
    Coded,
    /// <summary>T1.6 Blocked tier: staged in /FixRecommendations/staged/ for the next runner boot.</summary>
    StagedForNextRestart,
    /// <summary>T1.6: CLI exceeded scope or post-apply verification failed; diff saved for review.</summary>
    AppliedFailed,
    /// <summary>Legacy alias kept for migration compat; equivalent to <see cref="StagedForNextRestart"/>.</summary>
    RestartRequested,
    /// <summary>Fix has fully landed and the underlying finding is resolved.</summary>
    Complete,
    /// <summary>Underlying finding cleared on its own; recommendation no longer needed.</summary>
    Pruned,
    /// <summary>Operator rejected the plan; no further action will be taken.</summary>
    Rejected,
}

/// <summary>
/// A structured fix plan produced by the FlowMonitor when a Critical finding has no
/// vetted in-process action handler. The plan is generated by a two-pass Copilot CLI
/// invocation: pass 1 produces a /plan-style structured Markdown document; pass 2 is a
/// fresh adversarial "rubber-duck" review that scores confidence 0.0–1.0 and challenges
/// every assumption. The merged Markdown is persisted to SQLite + the
/// <c>/FixRecommendations/</c> folder, and surfaced on the Approvals page so a human
/// can review, rework (third Copilot pass with feedback), approve, or reject.
/// </summary>
public sealed record FixRecommendation
{
    public required string Id { get; init; }
    public required string FindingId { get; init; }
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public DateTimeOffset UpdatedAt { get; init; } = DateTimeOffset.UtcNow;
    public required string DetectorId { get; init; }
    public required FlowFindingSeverity Severity { get; init; }

    /// <summary>Confidence score from the rubber-duck pass (0.0–1.0). Default 0.5 if parsing failed.</summary>
    public double Confidence { get; init; } = 0.5;

    /// <summary>True when the fix touches a .cs source file or NuGet package — runner restart needed to activate.</summary>
    public bool NeedsRestart { get; init; }

    /// <summary>Comma-separated list of files the planner believes need to change. Free-form, may be empty.</summary>
    public string? FilesToChange { get; init; }

    /// <summary>
    /// T1.6: Tier classification computed by <see cref="FixClassifier"/> at insertion time
    /// (or lazily on first read for legacy rows). Drives the approve endpoint's apply path:
    /// Live → in-place CLI edit + auto-reload, DeferredRestart → CLI edit + restart prompt,
    /// Blocked → save to /FixRecommendations/staged/ for the next runner boot.
    /// Null only on rows persisted before T1.6.
    /// </summary>
    public FixTier? FixTier { get; init; }

    /// <summary>
    /// T1.6: Files extracted from the plan markdown (and structured FilesToChange line),
    /// normalised to forward-slash relative paths. Used by <see cref="FixClassifier"/> for
    /// tier routing AND by <c>LiveFixApplicator</c> as the scope allowlist for the constrained
    /// CLI run. Empty list means the planner could not identify any specific file.
    /// </summary>
    public IReadOnlyList<string>? AffectedFiles { get; init; }

    /// <summary>Planner's estimate of effort in minutes. May be null if not extracted.</summary>
    public int? EstimatedMinutes { get; init; }

    /// <summary>Full Markdown plan: pass 1 + rubber-duck critique stitched together. Always populated.</summary>
    public required string PlanMarkdown { get; init; }

    /// <summary>Absolute path to the persisted plan file under /FixRecommendations/, or null if file write failed.</summary>
    public string? PlanFilePath { get; init; }

    public FixRecommendationState State { get; init; } = FixRecommendationState.Draft;

    /// <summary>Operator-supplied feedback when requesting rework. Stored for audit and to seed the next planning pass.</summary>
    public string? OperatorFeedback { get; init; }

    /// <summary>Number of rework rounds the operator has requested for this recommendation.</summary>
    public int ReworkCount { get; init; }

    public DateTimeOffset? ResolvedAt { get; init; }

    /// <summary>If this recommendation eventually produced a PR (T1.6), the PR number is recorded here.</summary>
    public int? PrNumber { get; init; }

    /// <summary>Type of action the fix recommends (restart-agent, nudge, approve-gate, edit-prompt, edit-code, etc.).</summary>
    public string? ActionType { get; init; }

    /// <summary>Safety level: safe (auto-approvable), caution (review recommended), human-required (must not auto-apply).</summary>
    public string? SafetyLevel { get; init; }

    /// <summary>Root cause evidence from diagnostic research (log excerpts, API state, git status).</summary>
    public string? DiagnosticEvidence { get; init; }
}
