using System.Text.RegularExpressions;
using AgentSquad.Core.GitHub;
using AgentSquad.Core.GitHub.Models;
using Microsoft.Extensions.Logging;

namespace AgentSquad.Agents;

/// <summary>
/// Manages engineering tasks as GitHub Issues instead of an EngineeringPlan.md file.
/// Each task is a GitHub issue with the "engineering-task" label and structured metadata
/// in the issue body (complexity, dependencies, parent issue link).
/// </summary>
internal sealed partial class EngineeringTaskIssueManager
{
    public const string TaskLabel = "engineering-task";
    public const string StatusPending = "status:pending";
    public const string StatusAssigned = "status:assigned";
    public const string StatusInProgress = "status:in-progress";

    private readonly IGitHubService _github;
    private readonly ILogger _logger;

    // In-memory cache refreshed from GitHub on LoadTasksAsync
    private List<EngineeringTask> _cache = new();
    private bool _cacheLoaded;

    public EngineeringTaskIssueManager(IGitHubService github, ILogger logger)
    {
        ArgumentNullException.ThrowIfNull(github);
        ArgumentNullException.ThrowIfNull(logger);
        _github = github;
        _logger = logger;
    }

    /// <summary>All tasks (cached). Call <see cref="LoadTasksAsync"/> first.</summary>
    public IReadOnlyList<EngineeringTask> Tasks => _cache;

    // ── Loading ──────────────────────────────────────────────────────────

    /// <summary>
    /// Load all engineering-task issues from GitHub (open + closed) into the in-memory cache.
    /// Call this once at startup and after major state changes.
    /// </summary>
    public async Task LoadTasksAsync(CancellationToken ct = default)
    {
        var openIssues = await _github.GetIssuesByLabelAsync(TaskLabel, "open", ct);
        var closedIssues = await _github.GetIssuesByLabelAsync(TaskLabel, "closed", ct);

        _cache = openIssues.Concat(closedIssues)
            .Select(MapIssueToTask)
            .OrderBy(t => t.Id, StringComparer.OrdinalIgnoreCase)
            .ToList();

        _cacheLoaded = true;
        _logger.LogInformation("Loaded {Count} engineering tasks from GitHub issues ({Open} open, {Closed} closed)",
            _cache.Count, openIssues.Count, closedIssues.Count);
    }

    /// <summary>True if <see cref="LoadTasksAsync"/> has been called.</summary>
    public bool IsLoaded => _cacheLoaded;

    // ── Task Creation ────────────────────────────────────────────────────

    /// <summary>
    /// Create GitHub issues for a list of engineering tasks generated by the AI.
    /// Links each task as a sub-issue of its parent PM issue using GitHub's Sub-Issues API.
    /// Returns the created tasks with IssueNumber and GitHubId populated.
    /// </summary>
    public async Task<List<EngineeringTask>> CreateTaskIssuesAsync(
        IReadOnlyList<EngineeringTask> tasks, CancellationToken ct = default)
    {
        var created = new List<EngineeringTask>();

        foreach (var task in tasks)
        {
            var body = BuildIssueBody(task);
            var labels = new[] { TaskLabel, $"complexity:{task.Complexity.ToLowerInvariant()}", StatusPending };

            try
            {
                var issue = await _github.CreateIssueAsync(
                    $"[{task.Id}] {task.Name}", body, labels, ct);

                var updatedTask = task with
                {
                    IssueNumber = issue.Number,
                    GitHubId = issue.GitHubId,
                    IssueUrl = issue.Url,
                    Status = "Pending"
                };
                created.Add(updatedTask);
                _cache.Add(updatedTask);

                // Link as sub-issue of parent PM enhancement issue
                if (task.ParentIssueNumber.HasValue && issue.GitHubId > 0)
                {
                    await _github.AddSubIssueAsync(task.ParentIssueNumber.Value, issue.GitHubId, ct);
                }

                _logger.LogInformation("Created engineering task issue #{Number} for {TaskId}: {Name}",
                    issue.Number, task.Id, task.Name);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to create issue for task {TaskId}", task.Id);
            }
        }

        return created;
    }

    /// <summary>
    /// Create blocked-by dependency links between engineering tasks using GitHub's Dependencies API.
    /// Call after CreateTaskIssuesAsync and after resolving dependency issue numbers.
    /// </summary>
    public async Task LinkTaskDependenciesAsync(IReadOnlyList<EngineeringTask> tasks, CancellationToken ct = default)
    {
        // Build map from issue number → GitHubId for dependency resolution
        var issueNumToGitHubId = _cache
            .Where(t => t.IssueNumber.HasValue && t.GitHubId.HasValue)
            .ToDictionary(t => t.IssueNumber!.Value, t => t.GitHubId!.Value);

        foreach (var task in tasks)
        {
            if (!task.IssueNumber.HasValue || task.DependencyIssueNumbers.Count == 0)
                continue;

            foreach (var depIssueNum in task.DependencyIssueNumbers)
            {
                if (issueNumToGitHubId.TryGetValue(depIssueNum, out var blockingGitHubId))
                {
                    await _github.AddIssueDependencyAsync(task.IssueNumber.Value, blockingGitHubId, ct);
                }
            }
        }
    }

    // ── Queries ──────────────────────────────────────────────────────────

    /// <summary>Find the next assignable task matching complexity preferences with met dependencies.</summary>
    public EngineeringTask? FindNextAssignableTask(params string[] complexityPreferences)
    {
        foreach (var complexity in complexityPreferences)
        {
            var task = _cache.FirstOrDefault(t =>
                string.Equals(t.Complexity, complexity, StringComparison.OrdinalIgnoreCase)
                && t.Status == "Pending"
                && AreDependenciesMet(t));
            if (task is not null)
                return task;
        }
        return null;
    }

    /// <summary>Check if all dependency issues for a task are closed (Done).</summary>
    public bool AreDependenciesMet(EngineeringTask task)
    {
        if (task.DependencyIssueNumbers.Count == 0)
            return true;

        return task.DependencyIssueNumbers.All(depIssueNum =>
        {
            var dep = _cache.FirstOrDefault(t => t.IssueNumber == depIssueNum);
            return dep is null || IsTaskDone(dep);
        });
    }

    /// <summary>Check if ALL engineering tasks are done.</summary>
    public bool AreAllTasksDone() => _cache.Count > 0 && _cache.All(IsTaskDone);

    public int PendingCount => _cache.Count(t => t.Status == "Pending");
    public int InProgressCount => _cache.Count(t => t.Status is "Assigned" or "InProgress");
    public int DoneCount => _cache.Count(IsTaskDone);
    public int TotalCount => _cache.Count;

    public static bool IsTaskDone(EngineeringTask task) =>
        string.Equals(task.Status, "Done", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(task.Status, "Complete", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(task.Status, "closed", StringComparison.OrdinalIgnoreCase);

    // ── Status Transitions ───────────────────────────────────────────────

    /// <summary>Assign a task to an engineer: update title, set status:assigned label.</summary>
    public async Task AssignTaskAsync(int issueNumber, string engineerName, CancellationToken ct = default)
    {
        var idx = _cache.FindIndex(t => t.IssueNumber == issueNumber);
        if (idx < 0) return;

        var task = _cache[idx];
        var newTitle = $"{engineerName}: {task.Name}";
        var newLabels = ReplaceStatusLabel(task.Labels, StatusAssigned);

        await _github.UpdateIssueAsync(issueNumber, title: newTitle, labels: newLabels, ct: ct);

        _cache[idx] = task with { Status = "Assigned", AssignedTo = engineerName };
        _logger.LogInformation("Assigned task issue #{Number} ({Name}) to {Engineer}",
            issueNumber, task.Name, engineerName);
    }

    /// <summary>Mark a task in-progress and record its PR number in a comment.</summary>
    public async Task MarkInProgressAsync(int issueNumber, int prNumber, CancellationToken ct = default)
    {
        var idx = _cache.FindIndex(t => t.IssueNumber == issueNumber);
        if (idx < 0) return;

        var task = _cache[idx];
        var newLabels = ReplaceStatusLabel(task.Labels, StatusInProgress);

        await _github.UpdateIssueAsync(issueNumber, labels: newLabels, ct: ct);
        await _github.AddIssueCommentAsync(issueNumber, $"PR #{prNumber} created for this task.", ct);

        _cache[idx] = task with { Status = "InProgress", PullRequestNumber = prNumber };
    }

    /// <summary>Mark a task Done by closing the issue.</summary>
    public async Task MarkDoneAsync(int issueNumber, int? prNumber = null, CancellationToken ct = default)
    {
        var idx = _cache.FindIndex(t => t.IssueNumber == issueNumber);
        if (idx < 0) return;

        var task = _cache[idx];
        await _github.CloseIssueAsync(issueNumber, ct);

        _cache[idx] = task with
        {
            Status = "Done",
            PullRequestNumber = prNumber ?? task.PullRequestNumber
        };

        _logger.LogInformation("Marked task issue #{Number} ({Name}) as Done",
            issueNumber, task.Name);
    }

    /// <summary>Reset a task to Pending (e.g., after a failed PR close-and-recreate).</summary>
    public async Task ResetToPendingAsync(int issueNumber, CancellationToken ct = default)
    {
        var idx = _cache.FindIndex(t => t.IssueNumber == issueNumber);
        if (idx < 0) return;

        var task = _cache[idx];
        var newLabels = ReplaceStatusLabel(task.Labels, StatusPending);

        // Strip agent prefix from title back to just task name
        var cleanTitle = $"[{task.Id}] {task.Name}";
        await _github.UpdateIssueAsync(issueNumber, title: cleanTitle, labels: newLabels, state: "open", ct: ct);

        _cache[idx] = task with
        {
            Status = "Pending",
            AssignedTo = null,
            PullRequestNumber = null
        };

        _logger.LogInformation("Reset task issue #{Number} ({Name}) to Pending", issueNumber, task.Name);
    }

    /// <summary>Find a task by its issue number.</summary>
    public EngineeringTask? FindByIssueNumber(int issueNumber) =>
        _cache.FirstOrDefault(t => t.IssueNumber == issueNumber);

    /// <summary>Find a task by its task ID (e.g., "T1").</summary>
    public EngineeringTask? FindById(string taskId) =>
        _cache.FirstOrDefault(t => string.Equals(t.Id, taskId, StringComparison.OrdinalIgnoreCase));

    /// <summary>Find a task by name (for matching from PR titles).</summary>
    public EngineeringTask? FindByName(string name) =>
        _cache.FirstOrDefault(t => string.Equals(t.Name, name, StringComparison.OrdinalIgnoreCase));

    /// <summary>
    /// Find the first non-done task assigned to a specific engineer.
    /// Used by worker PEs to discover tasks assigned to them by the leader.
    /// </summary>
    public EngineeringTask? FindAssignedTo(string engineerName) =>
        _cache.FirstOrDefault(t =>
            !IsTaskDone(t)
            && t.Status is "Assigned" or "InProgress"
            && string.Equals(t.AssignedTo, engineerName, StringComparison.OrdinalIgnoreCase));

    /// <summary>
    /// Close any remaining open engineering task issues. Called during pipeline completion
    /// to ensure no task issues are left open (catches edge cases where MarkDoneAsync
    /// wasn't called or GitHub auto-close via "Closes #N" didn't fire).
    /// </summary>
    public async Task CloseAllRemainingTaskIssuesAsync(CancellationToken ct = default)
    {
        var remaining = _cache.Where(t =>
            !string.Equals(t.Status, "Done", StringComparison.OrdinalIgnoreCase) &&
            t.IssueNumber.HasValue).ToList();

        foreach (var task in remaining)
        {
            try
            {
                await _github.CloseIssueAsync(task.IssueNumber!.Value, ct);
                await _github.AddIssueCommentAsync(task.IssueNumber!.Value,
                    "✅ Closing — engineering pipeline complete. All tasks delivered.", ct);
                var idx = _cache.FindIndex(t => t.IssueNumber == task.IssueNumber);
                if (idx >= 0) _cache[idx] = task with { Status = "Done" };
                _logger.LogInformation("Closed remaining task issue #{Number} ({Name}) during pipeline completion",
                    task.IssueNumber, task.Name);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to close task issue #{Number} during cleanup", task.IssueNumber);
            }
        }
    }

    // ── Issue Body Parsing & Building ────────────────────────────────────

    private static string BuildIssueBody(EngineeringTask task)
    {
        return BuildIssueBodyWithDeps(task, task.DependencyIssueNumbers);
    }

    internal static string BuildIssueBodyWithDeps(EngineeringTask task, List<int> depIssueNumbers)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"## {task.Name}");
        sb.AppendLine();
        sb.AppendLine(task.Description);
        sb.AppendLine();
        sb.AppendLine("## Metadata");
        sb.AppendLine($"- **Task ID:** {task.Id}");
        sb.AppendLine($"- **Complexity:** {task.Complexity}");

        if (task.ParentIssueNumber.HasValue)
            sb.AppendLine($"- **Parent Issue:** #{task.ParentIssueNumber}");

        if (depIssueNumbers.Count > 0)
            sb.AppendLine($"- **Depends On:** {string.Join(", ", depIssueNumbers.Select(n => $"#{n}"))}");

        sb.AppendLine();
        sb.AppendLine("_Created by Principal Engineer._");
        return sb.ToString();
    }

    internal static EngineeringTask MapIssueToTask(AgentIssue issue)
    {
        var taskId = ParseTaskId(issue.Title) ?? $"T-{issue.Number}";
        var taskName = ParseTaskName(issue.Title) ?? issue.Title;
        var complexity = ParseComplexityFromLabels(issue.Labels);
        var status = issue.State.Equals("closed", StringComparison.OrdinalIgnoreCase)
            ? "Done"
            : ParseStatusFromLabels(issue.Labels);
        var assignedTo = ParseAssignedAgent(issue.Title);
        var deps = ParseDependencies(issue.Body);
        var parentIssue = ParseParentIssue(issue.Body);

        return new EngineeringTask
        {
            Id = taskId,
            Name = taskName,
            Description = ParseDescription(issue.Body),
            Complexity = complexity,
            Status = status,
            AssignedTo = assignedTo,
            IssueNumber = issue.Number,
            GitHubId = issue.GitHubId > 0 ? issue.GitHubId : null,
            IssueUrl = issue.Url,
            DependencyIssueNumbers = deps,
            ParentIssueNumber = parentIssue,
            Labels = issue.Labels.ToList()
        };
    }

    // ── Parsers ──────────────────────────────────────────────────────────

    /// <summary>Parse "[T1] Task name" → "T1"</summary>
    internal static string? ParseTaskId(string title)
    {
        var match = TaskIdPattern().Match(title);
        return match.Success ? match.Groups[1].Value : null;
    }

    /// <summary>Parse "[T1] Task name" or "Agent: Task name" → "Task name"</summary>
    internal static string? ParseTaskName(string title)
    {
        // Try "[T1] Name" format first
        var match = TaskIdPattern().Match(title);
        if (match.Success)
        {
            var afterBracket = title[(match.Index + match.Length)..].Trim();
            // May still have agent prefix: "Agent: Name"
            var agentMatch = AgentPrefixPattern().Match(afterBracket);
            return agentMatch.Success ? agentMatch.Groups[1].Value.Trim() : afterBracket;
        }

        // Try "Agent: Name" format
        var agentMatch2 = AgentPrefixPattern().Match(title);
        return agentMatch2.Success ? agentMatch2.Groups[1].Value.Trim() : null;
    }

    /// <summary>Parse agent name from "[T1] Agent: Name" or "Agent: Name"</summary>
    internal static string? ParseAssignedAgent(string title)
    {
        // Strip task ID prefix if present
        var match = TaskIdPattern().Match(title);
        var remaining = match.Success ? title[(match.Index + match.Length)..].Trim() : title;

        // Look for "Agent: TaskName" pattern
        var agentMatch = AgentPrefixPattern().Match(remaining);
        if (agentMatch.Success)
        {
            var agentName = remaining[..agentMatch.Index].Trim();
            if (agentName.EndsWith(':'))
                agentName = agentName[..^1].Trim();
            // The pattern captures what's after the colon; the agent name is before it
            var colonIdx = remaining.IndexOf(':');
            if (colonIdx > 0)
                return remaining[..colonIdx].Trim();
        }
        return null;
    }

    internal static string ParseComplexityFromLabels(IEnumerable<string> labels)
    {
        foreach (var label in labels)
        {
            if (label.StartsWith("complexity:", StringComparison.OrdinalIgnoreCase))
                return label["complexity:".Length..] switch
                {
                    "high" => "High",
                    "medium" => "Medium",
                    "low" => "Low",
                    var x => char.ToUpperInvariant(x[0]) + x[1..]
                };
        }
        return "Medium";
    }

    internal static string ParseStatusFromLabels(IEnumerable<string> labels)
    {
        foreach (var label in labels)
        {
            if (string.Equals(label, StatusAssigned, StringComparison.OrdinalIgnoreCase))
                return "Assigned";
            if (string.Equals(label, StatusInProgress, StringComparison.OrdinalIgnoreCase))
                return "InProgress";
            if (string.Equals(label, StatusPending, StringComparison.OrdinalIgnoreCase))
                return "Pending";
        }
        return "Pending";
    }

    internal static List<int> ParseDependencies(string? body)
    {
        if (string.IsNullOrWhiteSpace(body))
            return new();

        var match = DependsOnPattern().Match(body);
        if (!match.Success)
            return new();

        return IssueNumberPattern().Matches(match.Groups[1].Value)
            .Select(m => int.Parse(m.Groups[1].Value))
            .ToList();
    }

    internal static int? ParseParentIssue(string? body)
    {
        if (string.IsNullOrWhiteSpace(body))
            return null;

        var match = ParentIssuePattern().Match(body);
        return match.Success ? int.Parse(match.Groups[1].Value) : null;
    }

    internal static string ParseDescription(string? body)
    {
        if (string.IsNullOrWhiteSpace(body))
            return "";

        // Extract text between the first heading and "## Metadata"
        var lines = body.Split('\n');
        var desc = new System.Text.StringBuilder();
        bool pastFirstHeading = false;

        foreach (var line in lines)
        {
            if (line.TrimStart().StartsWith("## Metadata"))
                break;
            if (line.TrimStart().StartsWith("## ") && !pastFirstHeading)
            {
                pastFirstHeading = true;
                continue;
            }
            if (pastFirstHeading)
                desc.AppendLine(line);
        }

        return desc.ToString().Trim();
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private static string[] ReplaceStatusLabel(List<string> currentLabels, string newStatus)
    {
        var result = currentLabels
            .Where(l => !l.StartsWith("status:", StringComparison.OrdinalIgnoreCase))
            .Append(newStatus)
            .ToArray();
        return result;
    }

    // ── Regex patterns ───────────────────────────────────────────────────

    [GeneratedRegex(@"\[([A-Z0-9\-]+)\]\s*")]
    private static partial Regex TaskIdPattern();

    [GeneratedRegex(@"^.+?:\s*(.+)$")]
    private static partial Regex AgentPrefixPattern();

    [GeneratedRegex(@"\*\*Depends On:\*\*\s*(.+)", RegexOptions.IgnoreCase)]
    private static partial Regex DependsOnPattern();

    [GeneratedRegex(@"#(\d+)")]
    private static partial Regex IssueNumberPattern();

    [GeneratedRegex(@"\*\*Parent Issue:\*\*\s*#(\d+)", RegexOptions.IgnoreCase)]
    private static partial Regex ParentIssuePattern();
}
