using AgentSquad.Core.Agents.Decisions;

namespace AgentSquad.Core.Configuration;

/// <summary>
/// Configuration for the decision impact classification and gating system.
/// Controls which impact levels require human approval before agents proceed.
/// </summary>
public class DecisionGatingConfig
{
    /// <summary>
    /// Master switch. When false, no decisions are gated — all auto-proceed.
    /// When true, decisions at or above <see cref="MinimumGateLevel"/> require human approval.
    /// </summary>
    public bool Enabled { get; set; } = false;

    /// <summary>
    /// Minimum impact level that requires human gate.
    /// "L" means L and XL are gated. "M" means M, L, XL. "XS" gates everything. "None" disables gating.
    /// </summary>
    public string MinimumGateLevel { get; set; } = "L";

    /// <summary>
    /// When true, gated decisions include a structured implementation plan generated by an extra AI turn.
    /// </summary>
    public bool RequirePlanForGated { get; set; } = true;

    /// <summary>
    /// Maximum extra AI deliberation turns for classifying and planning a decision.
    /// Prevents cost spiral. Turn 1 = classification, Turn 2 = plan generation.
    /// </summary>
    public int MaxDecisionTurns { get; set; } = 2;

    /// <summary>
    /// Minutes to wait for human response on a gated decision before auto-approving.
    /// 0 = wait indefinitely.
    /// </summary>
    public int GateTimeoutMinutes { get; set; } = 0;

    /// <summary>
    /// Action when gate timeout expires: "auto-approve", "block", or "escalate".
    /// </summary>
    public string TimeoutFallbackAction { get; set; } = "auto-approve";

    /// <summary>
    /// Parse the <see cref="MinimumGateLevel"/> string to a <see cref="DecisionImpactLevel"/>.
    /// Returns null if gating is disabled or level is "None".
    /// </summary>
    public DecisionImpactLevel? GetMinimumGateLevel()
    {
        if (!Enabled) return null;

        return MinimumGateLevel?.Trim().ToUpperInvariant() switch
        {
            "XS" => DecisionImpactLevel.XS,
            "S" => DecisionImpactLevel.S,
            "M" => DecisionImpactLevel.M,
            "L" => DecisionImpactLevel.L,
            "XL" => DecisionImpactLevel.XL,
            "NONE" or null or "" => null,
            _ => DecisionImpactLevel.L, // default to L if unrecognized
        };
    }

    /// <summary>
    /// Check if a given impact level requires human gate based on current config.
    /// </summary>
    public bool RequiresGate(DecisionImpactLevel level)
    {
        var minLevel = GetMinimumGateLevel();
        if (minLevel is null) return false;
        return level >= minLevel.Value;
    }
}
